version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run sls:deploy
  post_build:
    commands:
      - npm run sls:online:migrate
